# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/auth.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10proto/auth.proto\"\x0f\n\rEmptyResponse\"!\n\x10VerifyJWTRequest\x12\r\n\x05token\x18\x01 \x01(\t\"/\n\x0cLoginRequest\x12\r\n\x05\x65mail\x18\x01 \x01(\t\x12\x10\n\x08password\x18\x02 \x01(\t\"\x1e\n\rLoginResponse\x12\r\n\x05token\x18\x01 \x01(\t\"^\n\x13RegistrationRequest\x12\r\n\x05\x65mail\x18\x01 \x01(\t\x12\x10\n\x08nickname\x18\x02 \x01(\t\x12\x14\n\x0cphone_number\x18\x04 \x01(\t\x12\x10\n\x08password\x18\x05 \x01(\t\"%\n\x14RegistrationResponse\x12\r\n\x05token\x18\x01 \x01(\t\"&\n\x15\x46orgotPasswordRequest\x12\r\n\x05\x65mail\x18\x01 \x01(\t\"R\n\x15\x43hangePasswordRequest\x12\r\n\x05\x65mail\x18\x01 \x01(\t\x12\x14\n\x0cold_password\x18\x02 \x01(\t\x12\x14\n\x0cnew_password\x18\x03 \x01(\t2\x99\x02\n\x0e\x41uthentication\x12&\n\x05Login\x12\r.LoginRequest\x1a\x0e.LoginResponse\x12.\n\tVerifyJWT\x12\x11.VerifyJWTRequest\x1a\x0e.EmptyResponse\x12;\n\x0cRegistration\x12\x14.RegistrationRequest\x1a\x15.RegistrationResponse\x12\x38\n\x0e\x46orgotPassword\x12\x16.ForgotPasswordRequest\x1a\x0e.EmptyResponse\x12\x38\n\x0e\x43hangePassword\x12\x16.ChangePasswordRequest\x1a\x0e.EmptyResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'proto.auth_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_EMPTYRESPONSE']._serialized_start=20
  _globals['_EMPTYRESPONSE']._serialized_end=35
  _globals['_VERIFYJWTREQUEST']._serialized_start=37
  _globals['_VERIFYJWTREQUEST']._serialized_end=70
  _globals['_LOGINREQUEST']._serialized_start=72
  _globals['_LOGINREQUEST']._serialized_end=119
  _globals['_LOGINRESPONSE']._serialized_start=121
  _globals['_LOGINRESPONSE']._serialized_end=151
  _globals['_REGISTRATIONREQUEST']._serialized_start=153
  _globals['_REGISTRATIONREQUEST']._serialized_end=247
  _globals['_REGISTRATIONRESPONSE']._serialized_start=249
  _globals['_REGISTRATIONRESPONSE']._serialized_end=286
  _globals['_FORGOTPASSWORDREQUEST']._serialized_start=288
  _globals['_FORGOTPASSWORDREQUEST']._serialized_end=326
  _globals['_CHANGEPASSWORDREQUEST']._serialized_start=328
  _globals['_CHANGEPASSWORDREQUEST']._serialized_end=410
  _globals['_AUTHENTICATION']._serialized_start=413
  _globals['_AUTHENTICATION']._serialized_end=694
# @@protoc_insertion_point(module_scope)
