version: '3'

services:
  db:
    image: postgres:16
    container_name: db
    environment:
      POSTGRES_PASSWORD: postgres
    volumes:
      - ./postgres:/docker-entrypoint-initdb.d
    ports:
      - 5432:5432

  auth_rest_gateway_service:
    build: ./auth_rest_gateway_service
    container_name: auth_rest_gateway_service
    working_dir: /app
    volumes:
      - ./auth_rest_gateway_service:/app
    command: bash -c "make"
    environment:
      DB_USER: "postgres"
      DB_PASSWORD: "postgres"
    ports:
      - 8000:8000
